### PR TITLE
Update Persian Language

### PR DESCRIPTION
**Pull request by amiroperator**

### CODE REVIEW

**Comment by LuckyCyborg** [comment]
BTW, what happen with the Language Changer links on RTL Layouts?

Those links are random ordered, not as the generator push them.

**Comment by amiroperator** [comment]
@LuckyCyborg They are fine :smile:

**Comment by LuckyCyborg** [comment]
Oh, maybe we should add something into Layouts. page dir command...

**Comment by amiroperator** [comment]
What is your mean ?

**Comment by LuckyCyborg** [comment]
Then, when I switch in persian, the Menu Items from Language Changer are random.

I expected a inverse list from the LTR Layouts

**Comment by amiroperator** [comment]
From beginning to persian and persian to end are ordered, I mean from fr to ru and cz to es
Persian just broke the order.
Now find the problem.
I need to go now :smiley:

**Comment by LuckyCyborg** [comment]
Okay

**Comment by LuckyCyborg** [comment]
@amiroperator I fixed myself the Language Menu problem, nothing to worry about, after my current pull-request.

**Comment by amiroperator** [comment]
how much is my language good

**Pull request merged**
