### PR TITLE
3.0 nova

### PR DESCRIPTION
**Pull request by ybtashfeen**

### CODE REVIEW

**Comment by jimgwhit** [comment]
What in the hell is this?

**Comment by DonWagner** [comment]
Hehe I thought that to...

**Comment by jimgwhit** [comment]
A freakin Fiasco

**Comment by daveismyname** [comment]
nope, not going to happen.

**Comment by LuckyCyborg** [comment]
@daveismyname yep, looks like our friend @ybtashfeen have to learn how to use GitHub, or at least to ask some questions...

**Pull request closed without merging**
