### PR TITLE
Remove the Core\View@renderModule support, improve the logic on Core\View@offsetGet and the properties getter

### PR DESCRIPTION
**Pull request by LuckyCyborg**
This Pull Request introduce a new class, called **Core\BaseView**, which is the base for **Core\View** and **Core\Template**, and contains their common logic. This way, the code of Rendering is simplified.

To note that this Pull Request remove the Compat Layer for **View::renderModule()**, its functionality being supported completely by **View::render()**, as its third parameter being the optional **Module** name, and for now we throw a meaningful Exception for.

Also to note that removing the Compat Layer for **View::renderModule()** sensible simplify the **Core\View** and **Core\Template**. 

Finally, this Pull Request introduce improvements on Routing.

### CODE REVIEW

**Comment by geomorillo** [comment]
go ahead no problem here

**Comment by LuckyCyborg** [comment]
@geomorillo 

> go ahead no problem here

Thanks, but the only "shocking news" introduced by this pull request is removing the support for deprecated **View::renderModule()**

Everything else are optimizations.

**Comment by daveismyname** [comment]
This change does not alter the normal use of render and renderTemplate does it?

**Comment by LuckyCyborg** [comment]
@daveismyname Of course not. The following commands works as usual via View's Facade:

View::fetch()
View::render()
View::renderTemplate()

**Pull request merged**
