### PR TITLE
Adjust the Czech Language files, improve the Language System, Core\Config and Validation\Translator

### PR DESCRIPTION
**Pull request by LuckyCyborg**
Like the title say.

### CODE REVIEW

**Comment by geomorillo** [comment]
It is not only the cz language

**Comment by LuckyCyborg** [comment]
Then which one is faulting also?

**Comment by geomorillo** [comment]
sorry only cz is faulty

**Comment by geomorillo** [comment]
it think the problem is with the folder there is no cz folder but cs

**Comment by geomorillo** [comment]
oh you fixed it ok

**Pull request merged**
