### PR TITLE
Introduce the ability to handle different Database\Connection instanc…

### PR DESCRIPTION
**Pull request by LuckyCyborg**
…es on Database\Model and Database\ORM\Model

### CODE REVIEW

**Comment by daveismyname** [comment]
usage example?

**Comment by LuckyCyborg** [comment]
@daveismyname 

In the app/Config.php could be defined multiple Database configuration entries. Considering that we add a new entry called 'custom', we have:

```php
namespace App\Models;

use Auth\Model as BaseModel;

use \stdClass;


class Users extends BaseModel
{
    protected $connection = 'custom';

    protected $table = 'users';

    protected $primaryKey = 'id';


    public function __construct()
    {
        parent::__construct();
    }

    ...
}
```

Or the Connection instance name could be given on Model instatiaton:

```php
namespace App\Models;

use Database\Model as BaseModel;

class Articles extends BaseModel
{
    public function __construct($connection = null)
    {
        parent::__construct($connection);
    }

    ...
}
```

```php
$model = new \App\Models\Articles('custom');

// Do something shiny with the Model instance.
```

**Comment by daveismyname** [comment]
Great, thanks.

**Comment by LuckyCyborg** [comment]
@daveismyname No problem.

**Comment by LuckyCyborg** [comment]
@daveismyname Please modify Release Notes the second Model example as I modified there.

For the Database API's Models is mandatory to specify the **table** and **primaryKey**.

**Comment by daveismyname** [comment]
Roger that, updated it.

I'm going to build novacasts using the new database api so that will give me good coverage when doing tutorials with.

**Comment by LuckyCyborg** [comment]
@daveismyname And another small mistake on second Model, the table should be **articles** not **users**. 

Uh oh, I need to start the computer, that tablet have its own mind.

And just ask if you want details about something...

**Comment by daveismyname** [comment]
ha no problem!

**Pull request merged**
