### PR TITLE
Update Language.php

### PR DESCRIPTION
**Pull request by amiroperator**
Edit Language.php

### CODE REVIEW

**Comment by geomorillo** [comment]
Can you please add spanish language?  "es" i forgot when adding the language file.

**Comment by amiroperator** [comment]
Sorry but I don't know spanish

**Comment by LuckyCyborg** [comment]
@amiroperator 

> Sorry but I don't know spanish

You have just to add to your patch the code for Spanish:

```php
, 'es'
```

**Comment by geomorillo** [comment]
thanks

**Pull request merged**
