### PR TITLE
Adjust Language

### PR DESCRIPTION
**Pull request by amiroperator**

### CODE REVIEW

**Comment by LuckyCyborg** [comment]
Just curious how is said 'Yup' in Persian, using latin chars... :smirk:

BTW, good Job! :+1:

**Comment by LuckyCyborg** [comment]
@amiroperator Just nitpicking about the writing style: Why not one space before 'direction' instead of four, on app/Config.php?

Also, look on aligments of variables into Core\Language.

**Comment by amiroperator** [comment]
@LuckyCyborg I think it is : /ɑːr/ /ɛ/ 
ar in mars
e in rex
آره
Aaree
I don't know how to explain

**Comment by amiroperator** [comment]
There is some an error in your last commits:
2016-05-18 17:23PM - The use statement with non-compound name 'Event' has no effect in E:\Amir\Projects\nova\app\Events.php on line 9

check it

**Comment by daveismyname** [comment]
I'm concerned about loading in from raw.githubusercontent.com:

````
https://raw.githubusercontent.com/AbdullahDiaa/Bootstrap-RTL/master/bootstrap.rtl.min.css
````

If anything is changed on your repo it will effect this, better to use a CDN.

Also that is using v3.0.3 the current version is v3.3.6 (I'll be updating the current cdn version)

**Comment by amiroperator** [comment]
I will update them please don't merge this PR

**Comment by daveismyname** [comment]
OK thanks.

**Comment by amiroperator** [comment]
I have this error:
2016-05-18 17:23PM - The use statement with non-compound name 'Event' has no effect in E:\Amir\Projects\nova\app\Events.php on line 9
and I fixed it with by adding an 'as Event' at end of 'use Event;'

may I add fixes to this PR ?

**Comment by LuckyCyborg** [comment]
@amiroperator Look on Aliases configuration on app/Config.php

Check against ***app/Config.example.php**

Myself I can't reproduce the problem.

**Comment by daveismyname** [comment]
I'm closing the PR is it's out of sync now.

**Pull request closed without merging**
