### PR TITLE
Move configurations in to separate files

### PR DESCRIPTION
**Pull request by amiroperator**

### CODE REVIEW

**Comment by LuckyCyborg** [comment]
@amiroperator I agree in principle with this change, but please use the directory **Config** not **Configs**.

Also, let's to see @daveismyname opinion about this thing. I for one, I'm in.

**Comment by amiroperator** [comment]
I just did it because of better organization

**Comment by LuckyCyborg** [comment]
@amiroperator Thanks, but also where I am myself on Authors? 

Behind the SMVC v2.2 configuration, I'm the one who write those configurations... :smirk:

**Comment by amiroperator** [comment]
@LuckyCyborg Which config ?

**Comment by LuckyCyborg** [comment]
'Configs/Language.php';
'Configs/Module.php';
'Configs/ClassAliases.php';
**Config::set()** part of 'Configs/Database.php';
'Configs/Auth.php';
'Configs/Cache.php'; 

And no, I do not see Edwin Hoksberg sending patches for them...

**Comment by LuckyCyborg** [comment]
@amiroperator Thanks, but i forgot about app/Config/Module.php

**Comment by amiroperator** [comment]
@LuckyCyborg You are welcome :smile:

**Comment by LuckyCyborg** [comment]
BTW, please rename the Modules configuration as **app/Config/Modules.php**, is more logic.

**Comment by amiroperator** [comment]
Anything else ?

**Comment by daveismyname** [comment]
> BTW, please rename the Modules configuration as app/Config/Modules.php, is more logic.

would that not apply to languages and databases.

I'm happy to have this, it's more organised and reduces the length of the class.

**Comment by LuckyCyborg** [comment]
Please move the defines from app/Config/Database.php to base app/Config.php file.

I guess @daveismyname will argue about that, because he have videos about, and it is important that defines to not be overridden from mistake.

**Comment by amiroperator** [comment]
Let him come and say what is the best :smile:

**Comment by daveismyname** [comment]
> I guess @daveismyname will argue about that, because he have videos about, and it is important that defines to not be overridden from mistake.

No that makes sense, I'll be covering these anyway but this is what makes me nervous about making new videos with all the changes.

**Comment by LuckyCyborg** [comment]
@daveismyname We leave the Database as singular, is about Database API

But, about Languages, yes!

BTW, you agree to leave the Database defines into app/Config/Database.php ?

**Comment by daveismyname** [comment]
> BTW, you agree to leave the Database defines into app/Config/Database.php ?

Makes more sense to have them in base config

**Comment by LuckyCyborg** [comment]
Then, let's leave them in the app/Config.php

**Comment by amiroperator** [comment]
@daveismyname So, Should I move them into base config ?

**Comment by daveismyname** [comment]
Yep.

**Comment by LuckyCyborg** [comment]
@daveismyname BTW, please merge that: https://github.com/nova-framework/framework/pull/870

Nothing spectacular, I started integration of new Request API on Validation\Validator this time.

**Comment by LuckyCyborg** [comment]
@amiroperator and @daveismyname I propose also **app/Config/Languages.php**

It is about all know languages, after all...

**Comment by LuckyCyborg** [comment]
@amiroperator About renaming **app/Config/Language.php** as **app/Config/Languages.php**

**Comment by daveismyname** [comment]
Don't forget to update the require paths in Config.php

**Comment by amiroperator** [comment]
Oh yeah sorry

**Comment by daveismyname** [comment]
let me know once it's completed and I'll merge it.

**Comment by amiroperator** [comment]
Done

**Comment by LuckyCyborg** [comment]
Update also the requires from app/Config.php which points to Configs not to Config directory

**Comment by jimgwhit** [comment]
@daveismyname and @LuckyCyborg what is the deal with this PR, Having the require like that is same as having all in one file like it is now, so why, is the OP just wanting to add un-nessary files not needed.  Sorry, someone has to be frank with this stuff, we did not win WW2 by being nice.

**Comment by daveismyname** [comment]
Yes all code could be placed in a single file for the entire framework, does not mean it's advisable.

WW2 has fuck all to do with this!!!

**Comment by amiroperator** [comment]
@daveismyname I don't know if you like it merge it

**Comment by LuckyCyborg** [comment]
@jimgwhit When the Lead Developer and myself, which I like to claim to be one of the main developers agree with this this, how you dare to start your usual political speech?

Look, there is your favorite Nova version: https://github.com/nova-framework/framework/releases/tag/v3.0

Please stuck in that version and be kind to shut-up!

**Comment by daveismyname** [comment]
the CACHEPATH define should also be moved the base config that way all defined are in one place.

**Comment by LuckyCyborg** [comment]
@daveismyname Yep!

**Comment by jimgwhit** [comment]
> When the Lead Developer and myself, which I like to claim to be one of the main developers of Nova, both agree with those changes, how you dare to start your usual political speech?

The lead developer made a easy, simple framework, yet very powerful. You are turing it into a cluster f.  It is to the point where a new person to the framework is finding it harder to understand.  The keep it simple went by the wayside.

**Comment by daveismyname** [comment]
Whilst there is more built into this now I believe it's still easy to use, the older techniques are still in place. Updated documentation and videos will help to explain the various aspects.

**Comment by jimgwhit** [comment]
I do appreciate the PR's not breaking stuff.  I have said Lucky is a good programmer. I just like writing my own auth, etc. Don't understand why some stuff has to be in framework instead of optional.

**Comment by amiroperator** [comment]
@jimgwhit 

>  I just like writing my own auth,

I agree with that

**Comment by daveismyname** [comment]
You still can, you are not forced to make use of Auth the usage demo is a module that can be ignored or even turned off/removed without any problems.

I too write my own but for those who don't understand how yet this can prove useful at the very least as a usage example.

**Comment by jimgwhit** [comment]
@amiroperator I see your reasoning on the pr, either way works. All I mean is YES have a AUTH package that one coul pull in with composer.  There are many thing crammed into frameworks that are not used in / on every site.  Have them available, but why have them in the framework. 

If Joe don't feel he is good enough to write his own code for auth, then composer in the package that Lucky has. Whereas Billy BoB might have his own auth.  
No telling what Sally Mae will do.

**Comment by LuckyCyborg** [comment]
@daveismyname Please create a new repository called **base-framework** and push the current master on it. 

I will strip there the framework from everything, until bare metal as in Routing, Controllers and Views, just to make this guy stop this speeches. 

Or, Jim, even Views you do not need? if so, just say it.

**Comment by jimgwhit** [comment]
@LuckyCyborg Take a breath, it is ok, I liked your last two PR's, request stuff, I agree, it was great, you are the Man.

**Comment by amiroperator** [comment]
@LuckyCyborg 

> Please create a new repository called base-framework and push the current master on it.

I appreciate that

**Comment by jimgwhit** [comment]
> Please create a new repository called base-framework and push the current master on it. 

No don't do that. @LuckyCyborg are you OK now?

**Comment by Kingorgg** [comment]
I approve of this PR

**Comment by jimgwhit** [comment]
@LuckyCyborg come out come out where ever you are.

**Comment by Kingorgg** [comment]
@jimgwhit Then wait for the docs from Myself or @daveismyname

**Comment by jimgwhit** [comment]
@Kingorgg already existing framework, A PR should be well documented, look at this from laravel
```
Basic Input

You may access all user input with a few simple methods. You do not need to worry about the HTTP verb used for the request, as input is accessed in the same way for all verbs.
Retrieving An Input Value

$name = Input::get('name');

Retrieving A Default Value If The Input Value Is Absent

$name = Input::get('name', 'Sally');

Determining If An Input Value Is Present

if (Input::has('name'))
{
    //
}

Getting All Input For The Request

$input = Input::all();

Getting Only Some Of The Request Input

$input = Input::only('username', 'password');

$input = Input::except('credit_card');
```
All I ask is for good detailed instructions on a PR. As an example one had a controller example, you remember, but no usage else where. That is the one a while back you helped me solve. And I appreciate it.

**Comment by LuckyCyborg** [comment]
@jimgwhit 

> @LuckyCyborg Take a breath, it is ok

Huh? I say that I will maintain a "official" fork on Nova, that bare-metal which you profess there, just for your use, and you refuse the offer?

**Comment by LuckyCyborg** [comment]
@Kingorgg Thanks, Mr. Daniel **Taylor**, for your kind intentions!

**Comment by jimgwhit** [comment]
@LuckyCyborg fine if you want to, may be a good idea. Sorry I did not know AUTH was in a demo only. I have been real busy writing a custom accounting package, so many PR's to keep up with.

**Comment by LuckyCyborg** [comment]
The part from App is in a Module, deletable in several seconds. 

The part from System is isolated in its own namespace, don't want top use it, it stay quietly in its bunch.

**Comment by jimgwhit** [comment]
@LuckyCyborg was I correct, were you pacing back and forth? ha ha

**Comment by LuckyCyborg** [comment]
@jimgwhit Nope. Meantime, I talked with some colleagues, about some of my tasks. I'm at job.

**Comment by jimgwhit** [comment]
A final word, I will say @LuckyCyborg is good at adding in something without breaking existing code.

**Comment by LuckyCyborg** [comment]
I'm habituated to work over a stable tree, where API preservation is a must. After all, I earn my food from writing PHP code since the previous millennium, with a reason.

**Pull request merged**
