### PR TITLE
Minify html page output

### PR DESCRIPTION
**Pull request by amiroperator**
A simple function to minify html page output.
Remove white-spaces from the HTML with the help ob_start's buffer

### CODE REVIEW

**Comment by LuckyCyborg** [comment]
While wonderful Idea, I do not agree with idea to mess with Framework's bootstrap and Gods forbid! to install custom buffer handlers. 

That should be done via Middleware, WHEN every user will pass to new APIs.

**Comment by amiroperator** [comment]
So I can make it work with a config if that was true
what do you say ?

**Comment by LuckyCyborg** [comment]
Nope. It will conflict with Response API.

Please keep this good code for later times. 

I will ask you about it, in the future, to be added to Middleware.

For now, the final response is: NO

**Comment by LuckyCyborg** [comment]
BTW, the Helper per-se,  you can preserve in.

**Comment by LuckyCyborg** [comment]
But, remove any changes to the Framwork's bootstrap.

**Comment by amiroperator** [comment]
Do you have a messenger or something to talk better ?

I need talk with you with something

I closed this for later

**Comment by daveismyname** [comment]
There is this chat you can use. http://novaframework.com/chat

**Comment by LuckyCyborg** [comment]
> I need talk with you with something

Use that, it have also private rooms:

 https://gitter.im/nova-framework/framework

**Comment by amiroperator** [comment]
Thanks

**Comment by LuckyCyborg** [comment]
No problem

**Comment by amiroperator** [comment]
I'll be in touch with you there

**Comment by LuckyCyborg** [comment]
Ok

**Pull request closed without merging**
