### PR TITLE
Improve Database\Model and add a (dedicated) QueryBuilder for it

### PR DESCRIPTION
**Pull request by LuckyCyborg**
This pull-request introduce a improvement of **Database\Model** and add a dedicated **QueryBuilder** for it, in the same time simplifying and consolidating the **Database\Query\Builder**.

To note that the code represent a back-porting of the related optimizations present on **Nova 4** and basically does not introduce API changes, then it could qualify for a micro version increase.

### CODE REVIEW

**Comment by daveismyname** [comment]
Does this offer a usage change or it is internal change only?

**Comment by LuckyCyborg** [comment]
@daveismyname Basically, it is internal change only, but also make a useful method available to **Database\Model** associated QueryBuilder, aka **findMany()**.

That's all the visible changes.

**Comment by daveismyname** [comment]
👍

**Comment by LuckyCyborg** [comment]
@daveismyname Thanks!

**Pull request merged**
