### PR TITLE
3.0 nova

### PR DESCRIPTION
**Pull request by jcmarin2298**

### CODE REVIEW

**Comment by jimgwhit** [comment]
What is the deal with all these comments some of them apply to the branch that was completely removed the Nova beta that was on there for a while totally confused as to what the deal is with these comments. Also puzzled. Also overwhelmed.

**Comment by daveismyname** [comment]
@jimgwhit that's for @LuckyCyborg 3.0-nova branch.

**Comment by LuckyCyborg** [comment]
@daveismyname Huh? If I understand rigth, @jcmarin2298 want to merge my personal branch into master?

**Comment by daveismyname** [comment]
oh yes, I misread it!!!!

There is way too many changed to even begin to look at this one.

**Comment by jcmarin2298** [comment]
Sorry my bad.  Im a noob.

Sent from mobile

On Apr 9, 2016 12:09 PM, LuckyCyborg <notifications@github.com> wrote:

@daveismyname<https://github.com/daveismyname> Huh? If I understand rigth, @jcmarin2298<https://github.com/jcmarin2298> want to merge my personal branch into master?

**Pull request closed without merging**
