### PR TITLE
Implementation of the Services support on Nova Framework

### PR DESCRIPTION
**Pull request by LuckyCyborg**
### Introduction

This pull request introduce the **Services** support on Nova Framework, now it running in the top a Laravel-like kernel called **Foundation\Application**.

### Changes on Design

While the inner work is changed substantially, and considerable improved, **the public API of the Framework remains unchanged**, with those notable exceptions:

To obtain a **Database\Connection** instance, instead of using:
```php
$connection = Connection::getInstance();
```
Should be used this way:
```php
$connection = DB::connection();
```
This change is required because now the Database Connections Management is made by a Service.

Second change is that now the **Routing** is also a **Service**, and could be called using the Facades **Route** and **Router**, which are equivalent. For example:
```php
use Router;

// The actual variant
Router::any('subpage', 'App\Controllers\Welcome@subPage');
```
```php
use Route;

// The second variant, which is equivalent
Route::any('subpage', 'App\Controllers\Welcome@subPage');
```

In other hand, there is introduced a new **Exception Handler Service**, which in **debug** mode, expose the errors via a **Whoops! Handler**.

Finally, there are introduced new APIs and Services for **Cache**, **Filesystem** (on top of **Symfony's Finder**) and Logging (on top of **Monolog**).

### Changes on Boot stage

Now Nova use for start-up the **app/Boot/Start.php**, while **app/Boot/Global.php** contains additional boot commands. 

On the files from **app/Boot/Environment** folder, the end-user can fine tune the Framework's boot, depending in the current environment.

The Framework's **Boot** structure was exposed to end-user for his/her complete control and fine tuning.

### CODE REVIEW

**Comment by daveismyname** [comment]
so I take it by the constant updates to this PR it's not ready and a WIP?

**Comment by LuckyCyborg** [comment]
@daveismyname 

> so I take it by the constant updates to this PR it's not ready and a WIP?

Improvements, improvements, improvements. 

For example, I introduced a Kernel side Middleware based on **Symfony HTTP Kernel**, simplifying the management of sessions, encryption/decryption of the cookies and other shiny things.

I even written a optional Mailer Handler for Logging.

**Comment by daveismyname** [comment]
OK let me know once it's fully ready I'll then take a look.

**Comment by LuckyCyborg** [comment]
@daveismyname 

> OK let me know once it's fully ready I'll then take a look.

You know that saying with hundred eyes are better than two?

The tree is stable, you are my guest to test it and find bugs. :smirk:

**Comment by daveismyname** [comment]
they can download and test I really don't have time to keep constantly checking it over and over I've been putting my other projects on hold to work on this, but as there is still no sign of PR's slowing down I cannot carry on like this.

There has been 21 commits alone today.

**Comment by jimgwhit** [comment]
I agree with @daveismyname let's get this one done get the thing stable of course a PR for a bug but other than that it would be nice not to have so many PR's and I've only said this 100 times now.  
I am in the process of migrating a version 2.2 over to Nova but so far I am still scared to use in production. But I will admit it is looking pretty darn good. Just don't understand the adding more and more and more all the time.  

@LuckyCyborg why don't you get a pencil and a piece of paper and write down all the other stuff you think it needs let Dave know get it in there and let's call this thing good for a while. 
And like I said maybe just a PR for a bug fix only for a while.

**Comment by jimgwhit** [comment]
The only bad thing about the new version is all of those symphony components they will only maintain them for so long before everything has to be updated that is the single thing I likeed about ver 2.2, had mainly PHP, PDO and standard stuff made it very easy to update and stay up-to-date with the latest PHP version now that there's a bunch of third-party components more difficult to keep updated. Course I tried to say this all along but you know how it goes sometimes no one will listen. Just look at basic PDO it has stayed stable for a long time.

**Comment by LuckyCyborg** [comment]
@daveismyname Okay, you can test that thing. I recommend you a fresh install first.

@jimgwhit You know what I do there? I write a freaking second Laravel for yours. And I expect at least some testing instead of some glorification of the two-two thing.

**Comment by jimgwhit** [comment]
@LuckyCyborg and @daveismyname why a time zone ordeal?  I have no problem changing in config to 
```
define('DEFAULT_TIMEZONE', 'America/Chicago');
```
Shouldn't any developer know this, if not they should become janitor.

**Comment by amiroperator** [comment]
I am waiting for stable version...

**Comment by daveismyname** [comment]
> @daveismyname Okay, you can test that thing. I recommend you a fresh install first.

I will once the PR's **stop**, there's been 6 since you posted that. You should work on your own fork and only do a PR when its ready.

Any arguing about this I will ignore I'm sick of saying it.

**Comment by LuckyCyborg** [comment]
@daveismyname 

> I will once the PR's stop, there's been 6 since you posted that. 

You looked what contains those 6 commits? Only one fixed a issue, while installing in a production server. This one: https://github.com/nova-framework/framework/pull/971/commits/4ef1b2914a28c9eb760a57214240b3cbf6ebe95a

The rest are fine tuning on Boot stage and adjusting comments (yeah, I do some comments on code).

If it is ready or not, test it and decide yourself. I do not know if it work on SAMBA, MAMBA, WAMP, XAMPP and PHP7 but I'm pretty sure that **it works in a real production server, under PHP 5.5 and it drive a CRM, starting four hours ago.** 

You are my guest to test it and see yourself how it works. Eventually to propose enhancements or patches to. :+1: 

> You should work on your own fork and only do a PR when its ready.

I would prefer them to be exposed also there, for **some testing**. And sometime, there are guys which pointed me to small problems. Which I really appreciate.

> Any arguing about this I will ignore I'm sick of saying it.

Why I should argue? Myself I arrived to my objectives and tomorrow I have to port on top of it another 4 site (including another CRM).

**Comment by jimgwhit** [comment]
Now I see the above on legacy session, I have been using new API. Am I supposed to go back now and use the original session helper.

**Comment by LuckyCyborg** [comment]
@jimgwhit 

> Now I see the above on legacy session, I have been using new API. Am I supposed to go back now and use the original session helper. 

No, you are supposed to do as you like. The initialization of the Legacy Session is made only to keep it working, the **Session API** being completely independent now. Basically, not iterraction.

**Pull request merged**
