### PR TITLE
add ordinal number function

### PR DESCRIPTION
**Pull request by woodsy1**

### CODE REVIEW

**Comment by LuckyCyborg** [comment]
So, what's the general utility of this **ordinal()** for Nova 3, considered that on Nova 4 using those static helpers is heavily not recommended?

I ask you, if you really want that **ordinal()**, it can't stay in your private **App\Helpers\Number** ?

Again, be kind to remember that Nova is not SMVC, but a Laravel 4 level of complexity Framework.

**Comment by woodsy1** [comment]
Sure it can be in private but it's a number function so fits best with
those other number helpers

**Comment by LuckyCyborg** [comment]
Again, what's the **general utility** of this **ordinal()** for Nova 3, considering that those Helpers are some "ancient" inheritance, targeted by me for deletion?

**Comment by daveismyname** [comment]
returns number with ordinal prefix such as 1st, 3rd, 5th.

The helpers in Nova 3 are not being deleted. We agreed they would not exist on Nova 4 not 3.

**Comment by LuckyCyborg** [comment]
> returns number with ordinal prefix such as 1st, 3rd, 5th.

And for what is util that?

**Comment by daveismyname** [comment]
what? I don't understand.

**Comment by LuckyCyborg** [comment]
I see the utility only in his particular app, which is something for gambling.

Give be a general utility for those which do not develop apps for games/sports with bets.

**Comment by daveismyname** [comment]
it's a number function, not specific to games/sports. It can be applied any type of leader board such as a sales team board for instance.

**Comment by LuckyCyborg** [comment]
> It can be applied any type of leader board such as a sales team board for instance.

It also apply to Farsi/Persian leader boards? No? Then I can consider it incomplete.

**Comment by daveismyname** [comment]
consider it any way you like.

**Comment by LuckyCyborg** [comment]
Oh, while we debate the utility of the **9th** wheel, how about https://github.com/nova-framework/framework/pull/1044 ?

Which introduce a really consistent improvement on Middleware, after all?

**Comment by daveismyname** [comment]
Sure I will have a look tonight, I'm at work now and don't have time to run through it.

**Comment by LuckyCyborg** [comment]
> Sure I will have a look tonight

As you wish, but be sure that you made your mind tomorrow.

This is my last working day before several weeks of... freedom!

**Comment by LuckyCyborg** [comment]
Also, I wonder why this new ordinal does not work at least on Romanian:

6 -> al saselea
7 -> al saptelea
8 -> al optulea
9 -> al noualea
10 -> al zecelea

Sorry, Dave, but your lead developer is a Romanian: me! 

Why that **ordinal()** do not give the Romanian ordinals, too? 

Not to talk also about Italian ordinals which out of respect it should give... :smirk:

**Comment by woodsy1** [comment]
Feel free to expand on it but I am Australian and know nothing about that!

**Pull request merged**
