### PR TITLE
Improve Assets

### PR DESCRIPTION
**Pull request by amiroperator**

### CODE REVIEW

**Comment by jimgwhit** [comment]
Will this PR affect people who don't ust hooks and autoloading of assets, i.e., some headers I still manually write out the link like:
```
<link href="<?php echo Helpers\Url::templatePath(); ?>css/style.css" rel="stylesheet">
<script type="text/javascript" src="<?php echo DIR; ?>public/js/jquery.js"></script> 
```
### I don't do it like this:
```
Assets::css([
    'https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css',
    'https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap-theme.min.css',
    'https://maxcdn.bootstrapcdn.com/font-awesome/4.6.3/css/font-awesome.min.css',
    Url::templatePath() .'css/style.css',
]);

echo $css;
```

**Comment by amiroperator** [comment]
@jimgwhit 

> Will this PR affect people who don't ust hooks and autoloading of assets

No

**Comment by LuckyCyborg** [comment]
@jimgwhit Looks like this PR do not affect the Nova behavior at all, second me.

**Comment by jimgwhit** [comment]
@LuckyCyborg OK.  
Sneak in a pagination question:
In new api pagination there is this
```
'data'         => $this->getCollection()->toArray(),
```
Say you are paginatiing 15 at a time, like example
```
$users = DB::table('users')->paginate(15);
```
Does query only pull 15 records from database at a time (efficient) or if there are 20,000 results
does it pull 20,000 results, put that in array and paginate array (not good)?  
I hope 15 only at a time is what is put into the array.

**Comment by LuckyCyborg** [comment]
@jimgwhit If a Laravel-ish method is implemented on Database API, it behave just like the original.

Go figure!

**Pull request merged**
