### PR TITLE
Initial commit of Language/Logs paths

### PR DESCRIPTION
**Pull request by LuckyCyborg**

### CODE REVIEW

**Comment by daveismyname** [comment]
should the language folder be set as well from en to En?

**Comment by LuckyCyborg** [comment]
Good point. To be honest, I would prefer that, for consistency... ;)

**Comment by daveismyname** [comment]
Ok lets change that too.

**Comment by LuckyCyborg** [comment]
@geomorillo Give me some time to go over paths, please...

**Pull request merged**
