### PR TITLE
Cleaned the Readme file and reorganised it.

### PR DESCRIPTION
**Pull request by Kingorgg**

### CODE REVIEW

**Comment by LuckyCyborg** [comment]
I would like to be eliminated all references to a installation on sub-directory. You seen too that a rookie can spend a day trying this simple way.

Let's grow up! Nova was designed for a certain way, and Dave presented an alternative style where the boot files respond from a sub-directory, but that's all.

Please, let's do not confuse the end-users and to be very clear on installation way: **above web-root** and end of story.

**Comment by LuckyCyborg** [comment]
@Kingorgg Thanks, Daniel!

**Comment by Kingorgg** [comment]
@LuckyCyborg No problem :+1:

**Comment by LuckyCyborg** [comment]
Still, will be nice to be specified very clear that the framework should be installed above web-root.

**Comment by jimgwhit** [comment]
@Kingorgg why do you think it's not secure under an htdocs folder on a shared host?  wouldn't that depend on the shared host company and their level of security?  If a server is hacked does it really matter where files are?  
I sincerely wish some of you people would stop listening to you-know-who so much.

**Comment by LuckyCyborg** [comment]
@jimgwhit 

> 22 whopping megabytes for some freaking themes

Let's be honest. Including the Bootstrap3 is about **34 whopping megabytes**.

> You know who should be considered a sabotage expert and an expert in espionage.

**My name is Cyborg. Lucky Cyborg.** (insert theme the movie's song)

**Comment by jimgwhit** [comment]
No the css standard is https://www.w3.org/standards/techs/css#w3c_all, and it shouldn't take 30mb to style a page. Apparently the person who wrote that adminlite thing is without freaking clue and hasn't seen
https://www.w3.org/standards/techs/css#w3c_all

**Comment by Kingorgg** [comment]
@jimgwhit It isn't all just css though is it? AdminLTE will also come with all the plugins, documentation and examples. So you can't just say that it is 30mb of css ...

**Comment by LuckyCyborg** [comment]
@jimgwhit 

The shipped Templates are truly optional, as demo about how is done. It is supposed to create your own Templates, and if you do not like, just remove the **AdminLTE** and **Bootstrap3** from **composer.json** and do your thing... :smirk: 

Or you suppose that I will have to write, for you, the needed Templates, gratis?

**Comment by LuckyCyborg** [comment]
@Kingorgg BTW, Daniel...

You have proposals for a Premium **Frontend** Theme?

**Comment by jimgwhit** [comment]
@Kingorgg how in the world did you manage any kind of Authentication before that was added into the framework Dave managed to do it I managed Authentication. It just took some sessions a couple crafty if constructs, but it did not take 30 megabytes to do it. I try so hard sometimes to be nice but I swear some of you people would not care if you know who maybe framework 20 Gigabytes in size good grief.

**Comment by jimgwhit** [comment]
> You have proposals for a Premium Frontend Theme?  

Yes css, write your own.

**Comment by LuckyCyborg** [comment]
@jimgwhit 

> Yes css, write your own.

We agree there. That is supposed to do you, as end-user: to write your own Templates and CSS.

**Comment by jimgwhit** [comment]
Then why the 30 megabyte thing?

**Comment by LuckyCyborg** [comment]
For you, demo; for me, what I need for my projects.

**Comment by daveismyname** [comment]
It's a DEMO use it YOU WANT TO if not REMOVE IT end of.

**Comment by LuckyCyborg** [comment]
:+1:

**Comment by jimgwhit** [comment]
Okay good to know I can exclude it from composer during an install thank you I did not know that.

**Comment by Kingorgg** [comment]
> why do you think it's not secure under an htdocs folder on a shared host? wouldn't that depend on the shared host company and their level of security? If a server is hacked does it really matter where files are?

I'm just going with what @LuckyCyborg has been saying all this time, and since he is someone that put quite a lot of effort to develop this framework, he should know what is a potential security vulnerability for it.

>  how in the world did you manage any kind of Authentication before that was added into the framework Dave managed to do it I managed Authentication. 

I coded the auth in my project myself, because all I need is something simple. I just delete the modules and anything I don't need as soon as I download the framework...

**Comment by jimgwhit** [comment]
@Kingorgg see previous comment it makes me happy I can not install that if I don't want to I was just going with whatever was in composer at first. The world was okay again.

**Comment by Kingorgg** [comment]
@jimgwhit Okay, no problem, I was in the middle of typing and didn't see the other comments. Everybody else replies too quickly. :-P

**Comment by daveismyname** [comment]
having all the files in the public is not secure, think about it the error.log and session files should not be accessible from a browser. We have problems with that in 2.2 remember the errorlog.html file can be accessed from the browser, this was a bad design, that has been corrected from 3.0.

 We are NOT talking about stopping HACKING that is a different topic altogether. If you are hacked then you have much bigger problems!.

**Comment by jimgwhit** [comment]
@Kingorgg concerning the other question one time I asked Dave about that and he did agree that really it's up to the hosting company and their security. But you know if someone wants the information bad enough they will get it somehow. And are you sure lucky can walk and chew gum at the same time. 

Somehow I managed to be a database manager at a trucking company using Java Technologies before I even heard of lucky.

**Comment by daveismyname** [comment]
> Somehow I managed to be a database manager at a trucking company using Java Technologies before I even heard of lucky.

what's your point?

**Comment by jimgwhit** [comment]
That I could care less about listening to what lucky  has to say. However I do value his opinion but you know what they say about opinions.

**Comment by jimgwhit** [comment]
Specifically what makes it insecure under htdocs it used to be fairly standard to put it there

**Comment by daveismyname** [comment]
See my comment above.

**Comment by daveismyname** [comment]
> That I could care less about listening to what lucky has to say. However I do value his opinion

that's a contradiction right there. It's sad you seem so bitter all the time.

**Comment by jimgwhit** [comment]
I try not to be bitter but it's like the authentication thing come on some people can roll their own Authentication instead of a pre-built package.  People want more and more and don't want to b
Roll up their sleeves and write their own stuff.

**Comment by daveismyname** [comment]
As said so many times it's optional, move on.

**Comment by jimgwhit** [comment]
Thanks and that was good to know and it's not required in composer.

**Comment by LuckyCyborg** [comment]
@daveismyname 

> having all the files in the public is not secure, think about it the error.log and session files should not be accessible from a browser

To note also that in future I have intention to introduce a **Smart Query Caching** feature on QueryBuilder, a very nice to have on speed-up a site.

Then, it is not only about **error.log** and **Session** files there, but also about the **Cache** files,  which will contains freaking confidential information, extracted directly from Database.

And, I do not know others, but in the World where I live, to put the **Cache** and **Session** files in live web is a reason enough to be fired. As in "go home right now, thanks for your services!" :smirk:

**Comment by jimgwhit** [comment]
> having all the files in the public is not secure, think about it the error.log and session files should not be accessible from a browser  

I cannot access error. Log in the browser since lucky implemented protective htaccess. Get a forbidden notice

**Comment by LuckyCyborg** [comment]
@jimgwhit 

While I tried to shield-up the Framework, it is still vulnerable to a server miss-configuration.

In case of server miss-configuration everything will be naked on web, including Cache, Logs, Sessions, Vendor.

**Pull request merged**
