### PR TITLE
Updated version number ...

### PR DESCRIPTION
**Pull request by Kingorgg**
in system/Foundation/Application

### CODE REVIEW

**Comment by daveismyname** [comment]
ah, yes this is updated in the release.

**Comment by LuckyCyborg** [comment]
@Kingorgg and @daveismyname Sorry for mess, but because it is a **const** I can't update on-fly, then we should manually adjust too.

**Comment by daveismyname** [comment]
Since you made me away I've been updating it in the releases must remember to do the source files too.

**Comment by LuckyCyborg** [comment]
@daveismyname The good part will be when we arrive with system on Composer package. Where this const will be hardcoded on package, while VERSION.txt will indicate the **nova-framework/app** too.

**Comment by LuckyCyborg** [comment]
@daveismyname BTW, you will hugely simplify the tasks of your end-users if you move the system to Composer package...

**Comment by LuckyCyborg** [comment]
@daveismyname Sadly, to move to Composer package with the system, while extremely simple to do, need a common namespace for it. 

Was not a luckiest decision to have the system components without a common namespace...

**Pull request merged**
