### PR TITLE
Implementation of a simple RTL Layout System

### PR DESCRIPTION
**Pull request by amiroperator**
This pull-request introduce a simple **RTL Layout System** for **right** alignment languages.

By adding a copy of a layout and adding a "-rtl" before **".php"** of name of that layout (e.g: "default-rtl.php"), the **Template** system will load exiting rtl layout instead of **"default.php"** when language direction is set to "RTL".

### CODE REVIEW

**Comment by LuckyCyborg** [comment]
Well, is a cool idea to auto-switch the templates to RTL, on **Core\Template** :+1:

**Comment by LuckyCyborg** [comment]
@amiroperator I suggest you to just ship the files on Template, into **Assets/css** directory, considering that there is no CDN for them.

And you could look to registering those files to a CDN, in future. Come on! Is about a entire Middle East usefulness there!

**Comment by LuckyCyborg** [comment]
Please change the language links menu with:

```php
<?php
$html = '';

foreach ($languages as $code => $info) {
    $html .= '<a href="' .site_url('language/' .$code) .'">' .$info['name'] .'</a> | ' .PHP_EOL;
}

echo rtrim(trim($html), ' |') .PHP_EOL;
?>
```

Where **$languages** are obtained on top of the files, from **Config::get('languages')**

**Comment by amiroperator** [comment]
@LuckyCyborg this is no related to this PR !

**Comment by daveismyname** [comment]
Sorry this needs updating now it's out of sync due to earlier PR's.

**Comment by amiroperator** [comment]
Still need changes... wait please...

**Comment by LuckyCyborg** [comment]
@amiroperator 

> this is not related to this PR !

You introduce new Layouts, and the said way is now how are rendered the Language Changer on Layouts, then is well related... :smirk:

**Comment by amiroperator** [comment]
@LuckyCyborg OH ! on new Layouts 

Right !

**Comment by LuckyCyborg** [comment]
@amiroperator You missed to get **$languages** on top of files:

```php
$languages = Config::get('languages');
```

**Comment by amiroperator** [comment]
You can merge it is ready

**Pull request merged**
