### PR TITLE
Template style alignment and Update Persian language

### PR DESCRIPTION
**Pull request by amiroperator**
Implementation of a simple direction system for template style
Update Persian Language

### CODE REVIEW

**Comment by LuckyCyborg** [comment]
Instead of
```php
$this->dir    = $info['dir'];
```
You should have 
```php
$this->dir    = $info['direction'];
```
According with you changes on Config.php

But I recommend also to use 'direction' instead of 'dir' into Language class

**Comment by LuckyCyborg** [comment]
Please format **Language::direction()** as following:
```php
public static function direction($code = LANGUAGE_CODE)
{
    $code = self::getCurrentLanguage($code);

    $languages = Config::get('languages');
        
    if(isset($languages[$code]) && ! empty($languages[$code])) {
         $info = $languages[$code];

         return $info['dir'];
    }

    return 'ltr';
}
```
Is more readable.

**Comment by amiroperator** [comment]
I tested that.
this code doesn't work because self::getCurrentLanguage($code); returns a first letter uppercase like Fa

**Comment by LuckyCyborg** [comment]
Now does NOT.

**Comment by pandory-network** [comment]
@LuckyCyborg 

`if (preg_match ('/[a-z]/', $cookie) && in_array($cookie, array_keys($languages))) {
     Session::set('language', ucfirst($cookie));
}`

set language cookie ucfirst

**Comment by LuckyCyborg** [comment]
Also, I tested a very simple thing:

Changing : 

```
<html lang="en">
```
TO
```
<html lang="en" dir="ltr">
```
and guess what? The page content switched to right alignment.

To configure automatically, we can do like bellow
```php
<html lang="<?php echo Langauge::code(); ?>" dir="<?= Language::direction(); ?>">
```

**Comment by LuckyCyborg** [comment]
@pandory-network 

> set language cookie ucfirst

That I should change, because go to more complex code.

**Comment by amiroperator** [comment]
@LuckyCyborg some bootstrap styles can't switched to right alignment.

**Comment by LuckyCyborg** [comment]
@amiroperator In fact I believe that there should be a **dedicated Template** for.

BTW, look there: https://github.com/zeroxme/bootstrap-3-arabic

Making the **Core\Language** direction aware is a good thing and I support it. 

But for a complete there should be Controllers which are Langauge direction aware, and to switch Templates.

It is possible to do it. Prepare you first a **DefaultArabic** Template on pair with Default one and we talk again about.

Then, remove the changes on Template and please keep only those in Language System.

**Comment by amiroperator** [comment]
@LuckyCyborg You mean we should make a special template for rtl templates ?

**Comment by LuckyCyborg** [comment]
Yep. A complete new one, specially for RTL Bootstrap, on pair with Default Template.

**Comment by amiroperator** [comment]
Would you like me to do that or you will do ?

**Comment by LuckyCyborg** [comment]
If you want RTL, you have to do it. After all, you are one able to appreciate when it works correctly, right?

And, like I said, using new View API, is possible to change the Templates on fly, via Controller's Middleware.

**Comment by amiroperator** [comment]
Should I close this PR and start over ?

**Comment by LuckyCyborg** [comment]
On this PR remove every change on Templates, and leave it for merging. 

I agree with the changes on Core\Language and Config.php.

**Comment by amiroperator** [comment]
Ok

**Comment by LuckyCyborg** [comment]
Your RTL version of Default should be called exactly: **DefaultRtl**

You see after WHY I ask that.

**Comment by LuckyCyborg** [comment]
Or, an alternative idea is to create two Layouts: **default-rtl.php** and **custom-rtl.php** on Default Template.

After I have the material to work and compare, we chose the best solution for RTL way.

**Comment by amiroperator** [comment]
I agree with that idea to create two Layouts

**Comment by LuckyCyborg** [comment]
Considering that the switching is possible only on new View API, I propose to start with those two Layouts.

After, we talk about the complete Template, but for now, do it those two Layouts.

**Comment by amiroperator** [comment]
It is easier to make a folder in default folder named rtl for rtl Layouts 

and in View API we can check if current language direction is set to rtl then load exiting rtl Layouts else  load default Layouts

What do you think ?

**Comment by LuckyCyborg** [comment]
@amiroperator Remained a change into **app/Templates/Default/header.php**

@daveismyname would not like that... :smirk:

**Comment by amiroperator** [comment]
9 commits is too much for a small change !

**Comment by LuckyCyborg** [comment]
@amiroperator That's perfect.

To remember to write those Layouts, first: **default-rtl.php** and **custom-rtl.php** on Default Template. 

Only they could be used under new **View API**.

**Comment by amiroperator** [comment]
Maybe tomorrow I am tired now

**Comment by LuckyCyborg** [comment]
Okay, no problem. 

It is late hour in Iran, right?

**Comment by amiroperator** [comment]
1:35 AM

**Comment by LuckyCyborg** [comment]
Good night, my Iranian friend! 

It is time to shutdown your computer, in my opinion... :smirk:

**Comment by amiroperator** [comment]
Good night.

**Pull request merged**
